In [1]:
import numpy as np
import matplotlib.pyplot as ply

In [2]:
m = 10000

x = np.random.normal(size=m)
X = x.reshape(-1,1)
y = 4.*x + 3. + np.random.normal(0,3,size=m)

In [3]:
x

array([ 0.45717153,  0.28893546, -1.62204093, ...,  0.33063419,
        1.56990192, -0.42342833])

In [4]:
X

array([[ 0.45717153],
       [ 0.28893546],
       [-1.62204093],
       ...,
       [ 0.33063419],
       [ 1.56990192],
       [-0.42342833]])

In [5]:
y

array([ 5.63761754,  3.00371835, -2.24999307, ...,  3.35780159,
       16.21799348,  4.60788607])

In [6]:
def J(theta,X_b,y):
    try:
        return np.sum((y - X_b.dot(theta)) ** 2) / len(y)
    except:
        return float('inf')

In [7]:
def dJ(theta,X_b,y):
    return X_b.T.dot(X_b.dot(theta) - y) * 2. / len(y)

In [10]:
def gradient_descent(X_b,y,initial_theta,eta,n_iters=1e4,epsilon=1e-8):
    theta = initial_theta
    cur_iter = 0
    
    while cur_iter < n_iters:
        gradient = dJ(theta,X_b,y)
        last_theta = theta
        theta = theta - eta * gradient
        if (abs(J(theta,X_b,y) - J(last_theta,X_b,y)) < epsilon):
            break
        cur_iter += 1
        
    return theta

In [12]:
%%time
X_b = np.hstack([np.ones((len(X),1)),X])
initial_theta = np.zeros(X_b.shape[1])
eta = 0.01
theta = gradient_descent(X_b,y,initial_theta,eta)

Wall time: 615 ms


In [14]:
theta

array([3.0133483 , 4.01693965])

## 随机梯度下降法

In [16]:
def dJ_sgd(theta,X_b_i,y_i):
    return X_b_i.T.dot(X_b_i.dot(theta) - y_i) * 2.

In [17]:
def sgd(X_b,y,initial_theta,n_iters):
    t0 = 5
    t1 = 50
    
    def learning_rate(t):
        return t0 / (t + t1)
    
    theta = initial_theta
    for cur_iter in range(n_iters):
        rand_i = np.random.randint(len(X_b))
        gradient = dJ_sgd(theta,X_b[rand_i],y[rand_i])
        theta = theta - learning_rate(cur_iter) * gradient
    return theta

In [20]:
%%time
X_b = np.hstack([np.ones((len(X),1)),X])
initial_theta = np.zeros(X_b.shape[1])

theta = sgd(X_b,y,initial_theta,len(X_b)//3)

Wall time: 155 ms


In [21]:
theta

array([2.9952328 , 4.02789731])

In [22]:
initial_theta


array([0., 0.])

In [23]:
initial_theta.shape

(2,)