In [3]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
x[3]

3

In [5]:
x[3:8]

array([3, 4, 5, 6, 7])

In [6]:
ind = [3,5,8]

In [7]:
x[ind]

array([3, 5, 8])

In [8]:
ind = np.array([[0,2],[1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [13]:
X = x.reshape([4,-1])

In [14]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [16]:
X[0,col]

array([1, 2, 3])

In [17]:
col = [True,False,True,True]
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

In [18]:
x<3


array([[ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [19]:
x = x.reshape(1)

ValueError: cannot reshape array of size 16 into shape (1,)

In [20]:
x = x.reshape(1,-1)

In [21]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [22]:
x.shape()

TypeError: 'tuple' object is not callable

In [23]:
x.shape

(1, 16)

In [24]:
x = np.arange(16)

In [25]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
np.sum(x <= 3)

4

In [27]:
np.count_nonzero(x <= 3)

4

In [28]:
np.any(x == 0)

True

In [29]:
np.all(x > 0)

False

In [30]:
x[x<5
]

array([0, 1, 2, 3, 4])