In [1]:
import numpy

In [2]:
numpy.__version__

'1.14.3'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.14.3'

## Python List 的特点

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
L[5]

5

In [9]:
L[5] = "Machine Learning"

In [10]:
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [11]:
import array
arr = array.array('i',[i for i in range(10)])

In [12]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5]

5

## numpy.array

In [15]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
nparr[5] = 'Ma'

ValueError: invalid literal for int() with base 10: 'Ma'

In [17]:
nparr.dtype

dtype('int32')

In [18]:
nparr[5] = 5.0

In [19]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
nparr[3] = 3.14


In [21]:
nparr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
nparr.dtype


dtype('int32')

In [23]:
nparr2 = np.array([1,2,3.0])

In [24]:
nparr2.dtype\


dtype('float64')

##其他创建 numpy.array的方法

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros(10).dtype

dtype('float64')

In [27]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.zeros(shape = (3,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.full(shape=(3,5),fill_value=666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

arange

In [46]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [48]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
np.arange(0,20,0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

##linspace

In [50]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [51]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

##random

In [52]:
np.random.randint(0,10)

4

In [53]:
np.random.randint(0,10,10)

array([5, 5, 9, 6, 0, 6, 8, 6, 5, 1])

In [54]:
np.random.randint(4,8,size=(3,5))

array([[5, 7, 7, 5, 5],
       [6, 7, 7, 4, 7],
       [4, 5, 7, 5, 5]])

In [55]:
np.random.seed(666)

In [56]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [57]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [59]:
np.random.random()

0.4628416859214477

In [60]:
np.random.random(10)

array([0.23340091, 0.76706421, 0.81995656, 0.39747625, 0.31644109,
       0.15551206, 0.73460987, 0.73159555, 0.8578588 , 0.76741234])

In [67]:
np.random.normal()

0.4407669166918434

In [68]:
np.random.normal(10,100)

79.33958697978164

In [69]:
np.random.normal(0,1,(3,5))

array([[ 0.03820097, -0.18592982, -0.35371521, -1.95332994, -0.34376486],
       [-1.47693162, -0.70022971,  0.77605168,  1.18063598,  0.06102404],
       [ 1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ,  0.03185388]])

In [71]:
np.random.normal?

In [72]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

In [83]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

##基本属性

In [85]:
x.ndim

1

In [88]:
X.ndim

2

In [90]:
x.shape

(10,)

In [91]:
X.shape

(3, 5)

In [92]:
x.size

10

In [93]:
X.size

15

### numpy.array的数据访问

In [3]:
x

NameError: name 'x' is not defined

In [2]:
x[0]

NameError: name 'x' is not defined