In [1]:
import numpy as np

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
X = np.arange(15).reshape(3,5)
X 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性

In [8]:
x.ndim

1

In [9]:
x[0]

0

In [10]:
X[0][0]

0

In [11]:
X[0]

array([0, 1, 2, 3, 4])

In [12]:
X[1]

array([5, 6, 7, 8, 9])

In [13]:
X[(1,1)]

6

In [14]:
x[1,1]

IndexError: too many indices for array

In [15]:
X[1,1]

6

In [16]:
x[0:5]

array([0, 1, 2, 3, 4])

In [17]:
x[:5]

array([0, 1, 2, 3, 4])

In [18]:
x[5:]

array([5, 6, 7, 8, 9])

In [19]:
x[:2,:3]

IndexError: too many indices for array

In [20]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [21]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [22]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [23]:
X[0]

array([0, 1, 2, 3, 4])

In [24]:
subX = X[:2,:3]

In [25]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [26]:
 subX = X[:2,:3].copy()

In [27]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [28]:
subX[0,0] = 100

In [29]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [30]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Reshape

In [31]:
x.shape

(10,)

In [32]:
x.ndim

1

In [33]:
X.ndim

2

In [34]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
A = x.reshape(2,5)

In [37]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
A.shape


(2, 5)

In [39]:
x.shape

(10,)

In [40]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## 合并与分割

In [41]:
x = np.array([1,2,3])

In [42]:
y = np.array([3,2,1])

In [43]:
x

array([1, 2, 3])

In [44]:
y

array([3, 2, 1])

In [45]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [46]:
z = np.array([6666,6,66,6])

In [47]:
np.concatenate([x,y,z])

array([   1,    2,    3,    3,    2,    1, 6666,    6,   66,    6])

In [48]:
A = np.array([[1,2,3],[4,5,6]])

In [49]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [52]:
B = np.array([1,2,3],[4,5,6],[7,8,9])

ValueError: only 2 non-keyword arguments accepted

In [53]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.concatenate([B,B])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
np.concatenate([B,B],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [57]:
np.concatenate([A,z.reshape(1,-1)])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [58]:
np.concatenate([A,z])

ValueError: all the input arrays must have same number of dimensions

In [59]:
np.concatenate([A,z.reshape(1,-1)])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [60]:
z

array([6666,    6,   66,    6])

In [61]:
np.concatenate([A,a.reshape(1,-1)])

NameError: name 'a' is not defined

In [62]:
a

NameError: name 'a' is not defined

In [63]:
np.concatenate([A,a.reshape(1,-1)])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [64]:
A2 = np.concatenate([A,x.reshape(1,-1)])

In [65]:
np.vstack([A,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [66]:
B = np.full((2,2),100)

In [67]:
B

array([[100, 100],
       [100, 100]])

In [68]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [69]:
x = np.arange(10)

In [70]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x1,x2,x3 = np.split(x,[3,7])
x1
x2
x3

array([7, 8, 9])

In [72]:
x1

array([0, 1, 2])

In [73]:
x2

array([3, 4, 5, 6])

## numpy.array中的运算

In [74]:
n = 10

In [75]:
L = [i for i in range(n)]

In [76]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
A = []
for e in L:

SyntaxError: unexpected EOF while parsing (<ipython-input-77-8a75cf02a9a9>, line 2)

In [ ]:
for e in L:
    A.a