## 聚合操作

In [1]:
import numpy as np 

L = np.random.random(100)

In [2]:
L

array([0.96458789, 0.8511581 , 0.35490989, 0.95820009, 0.66936116,
       0.10445445, 0.83301737, 0.32490384, 0.16550781, 0.8342562 ,
       0.79612551, 0.16088736, 0.6160449 , 0.4537787 , 0.44764986,
       0.65897244, 0.69156604, 0.09580043, 0.8370767 , 0.78272269,
       0.79225807, 0.45775492, 0.32613798, 0.22127798, 0.38656104,
       0.41797257, 0.29616899, 0.20526056, 0.03817289, 0.8216323 ,
       0.06287218, 0.5125355 , 0.82996546, 0.74522594, 0.01344268,
       0.76582926, 0.26992621, 0.25773321, 0.56779598, 0.61267484,
       0.78412196, 0.4367559 , 0.18654241, 0.74699473, 0.16607506,
       0.40939065, 0.25405822, 0.30692351, 0.09200389, 0.02897073,
       0.05338239, 0.65881919, 0.41673094, 0.00865008, 0.9420286 ,
       0.63194939, 0.04550404, 0.8308704 , 0.2103251 , 0.39010058,
       0.75550238, 0.93002661, 0.36022215, 0.75308429, 0.36830905,
       0.56654438, 0.85877071, 0.62946303, 0.51487524, 0.48412172,
       0.30528048, 0.92887658, 0.2408279 , 0.32549419, 0.48251

In [3]:
sum(L)

47.973602973635934

In [4]:
np.sum(L)

47.973602973635934

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

118 ms ± 298 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
797 µs ± 20.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np. min(big_array)

4.250580073472676e-07

In [7]:
X = np.arange(16).reshape(4,-1)

In [8]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.sum(X)

120

In [10]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [11]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [12]:
np.prod(X)

0

In [13]:
np.prod(X + 1)

2004189184

In [14]:
np.mean(X)

7.5

In [15]:
np.median(X)

7.5

In [16]:
v = np.array([1,1,2,2,10])

In [17]:
np.mean(v)

3.2

In [18]:
np.median(v)

2.0

In [20]:
np.percentile(big_array,q = 50)

0.5009594867562865

In [21]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big_array,q=percent))

4.250580073472676e-07
0.2496104441868838
0.5009594867562865
0.7503108981280459
0.9999985052708206


In [22]:
big_array

array([0.13889512, 0.17374053, 0.89899175, ..., 0.70150642, 0.20927944,
       0.63932472])

In [25]:
x = np.random.normal(0,1,size=1000000)

In [26]:
np.mean(x)

0.0005545715151846854

In [27]:
np.std(x)

1.0005881501177498

In [28]:
np.min(x)

-5.251271806691929

In [29]:
np.argmin(x)

662017

In [31]:
x[662017]

-5.251271806691929

### 排序和索引

In [32]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
np.random.shuffle(x)
x

array([ 5,  2,  9, 14, 13,  7, 11,  1,  0,  8, 10,  4, 12,  3, 15,  6])

In [35]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
x

array([ 5,  2,  9, 14, 13,  7, 11,  1,  0,  8, 10,  4, 12,  3, 15,  6])

In [37]:
x.sort()

In [38]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
X = np.random.randint(10,size=(4,4))
X

array([[8, 2, 0, 8],
       [9, 2, 9, 9],
       [8, 6, 4, 1],
       [2, 2, 4, 6]])

In [40]:
np.sort(X)

array([[0, 2, 8, 8],
       [2, 9, 9, 9],
       [1, 4, 6, 8],
       [2, 2, 4, 6]])

In [41]:
np.argsort(X)

array([[2, 1, 0, 3],
       [1, 0, 2, 3],
       [3, 2, 1, 0],
       [0, 1, 2, 3]], dtype=int64)

In [42]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
np.random.shuffle(x)

In [44]:
x

array([12,  1,  2, 14, 13,  8, 11, 10,  5,  4,  9, 15,  7,  3,  6,  0])

In [45]:
np.argsort(x)

array([15,  1,  2, 13,  9,  8, 14, 12,  5, 10,  7,  6,  0,  4,  3, 11],
      dtype=int64)

In [46]:
np.partition(x,3)

array([ 0,  1,  2,  3,  4,  8,  7,  6,  5,  9, 10, 15, 11, 13, 14, 12])

In [47]:
np.random.shuffle(x)

In [48]:
np.partition(x,3)

array([ 1,  0,  2,  3,  4,  5, 12,  7,  9, 10, 13,  8,  6, 11, 14, 15])