In [1]:
import numpy as np

In [5]:
a = np.array([0,1,8,1,4,2,7])

In [7]:
np.array([i for i in range(a.shape[0] - 1) if a[i+1] < a[i]])

array([2, 4])

In [6]:
b = a

In [7]:
b

array([0, 1, 2, 4])

In [8]:
a[0] = 100

In [9]:
a

array([100,   1,   2,   4])

In [10]:
b

array([100,   1,   2,   4])

In [11]:
c = a[:2]

In [12]:
c

array([100,   1])

In [13]:
c[0] = 0

In [14]:
a

array([0, 1, 2, 4])

In [15]:
b

array([0, 1, 2, 4])

array([0, 1])

In [27]:
def MergeFunc(arr1,arr2,arr):
        index1 = 0
        index2 = 0
        index = 0
        while(index < arr.shape[0]):
            while(index1 < arr1.shape[0]):
                if(arr1[index1] < arr2[index2]):
                    arr[index] = arr1[index1]
                    index1 += 1
                    index += 1
                else:
                    break

            if(index1 == arr1.shape[0]):
                for i in range(index2,arr2.shape[0]):
                    arr[index] = arr2[i]
                    index += 1
                break

            while(index2 < arr2.shape[0]):
                if(arr2[index2] <= arr1[index1]):
                    arr[index] = arr2[index2]
                    index2 += 1
                    index += 1
                else:
                    break

            if(index2 == arr2.shape[0]):
                for i in range(index1,arr1.shape[0]):
                    arr[index] = arr1[i]
                    index += 1
                break

In [55]:
arr1 = np.array([1,3,4,5,7,9,10,11])


In [56]:
arr2 = np.array([0,2,4,6,8])

In [57]:
arr = np.random.randint(0,10,arr1.shape[0]+arr2.shape[0])

In [58]:
MergeFunc(arr1,arr2,arr)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
a1 = 10
a2 = 20

In [61]:
a1,a2 = a2,a1

In [62]:
a1

20

In [63]:
np.ceil(5/2)

3.0

In [8]:
import numpy as np
class a:
    def __init__(self):
        self.initial_list_ = np.random.randint(0,10,10)
        self.len_ = self.initial_list_.shape[0]
        self.arr =  np.array([i for i in range(self.len_ - 1) if self.initial_list_[i+1] < self.initial_list_[i]])

In [9]:
A = a()

In [10]:
A.initial_list_

array([2, 5, 2, 4, 9, 6, 0, 0, 0, 0])

In [11]:
A.arr

array([1, 4, 5])

In [12]:
al = [0,1,2,3,4,5]

In [14]:
b = np.array([i for i in range(5) if al[i+1] < al[i]])

In [16]:
b.shape[0]

0